name: Deploy Infra Manually

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to deploy to'
        required: true
        default: 'Development'

jobs:
  deploy:
    name: 'Deploy to every environment'

    uses: evacalvogomez/cicd-tests/.github/workflows/template.yaml@main

    with:
      environment: ${{ inputs.environment }}
