name: Deploy Infra to Development

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to tags like v1.0.0, v2.3.4, etc.

jobs:
  deploy_dev:
    name: 'Deployment to Development'

    uses: evacalvogomez/cicd-tests/.github/workflows/template.yaml@main

    with:
      environment: Development
