name: Deploy Enviromental Data

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to tags like v1.0.0, v2.3.4, etc.

jobs:
  deploy_dev:
    name: 'Deployment to Development'

    uses: evacalvogomez/cicd-tests/.github/workflows/main.yaml@main
    with:
      environment: Development
      STAGE: dev
      S3_BUCKET_NAME: dev-mercury-enviromental-data
