name: Deploy Infra Manually

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to deploy to'
        required: true
        default: 'Development'

jobs:
  tag_check:
    runs-on: ubuntu-latest

    name: 'Check if tag exists'

    steps:
      - name: 'Check if tag exists'
        run: |
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "No tag found"
            exit 1
          fi

  deploy:
    name: 'Deploy to every environment'

    uses: evacalvogomez/cicd-tests/.github/workflows/template.yaml@main

    with:
      environment: ${{ inputs.environment }}
      bucket_prefix: 'mercury-enviromental-data'

    secrets: inherit
