name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.ORG_RELEASE_PLEASE_GITHUB_TOKEN }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false}, {"type":"fix","section":"Bug Fixes","hidden":false}, {"type":"chore","section":"Miscellaneous","hidden":false}, {"type":"infra","section":"Infrastructure","hidden":false}, {"type":"test","section":"Test","hidden":false}, {"type":"ci","section":"Continuous Integration","hidden":false}, {"type":"patch","section":"Patches","hidden":false}]'
