name: Deployment Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to deploy to'
        required: false
        default: 'Development'

jobs:
  deploy:
    name: 'AWS Infrastructure Deployment'

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Set Environment Variables
        run: |
          case ${{ inputs.environment }} in
            Development)
              echo "ENV_ALIAS=dev" >> $GITHUB_ENV
              ;;
            Staging)
              echo "ENV_ALIAS=staging" >> $GITHUB_ENV
              ;;
            Production)
              echo "ENV_ALIAS=prod" >> $GITHUB_ENV
              ;;
          esac

      - uses: actions/checkout@v4

      - name: Set variables
        env:
          ENV_TEST: ${{ vars.TEST }}
          ENV_SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run: |
          echo "$ENV_TEST"
