name: Deployment Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to deploy to'
        required: false
        default: 'Development'
      bucket_prefix:
        type: string
        description: 'Prefix for the bucket name'
        required: false

jobs:
  deploy:
    name: 'Testico'

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          case ${{ inputs.environment }} in
            Development)
              export ENV_ALIAS=dev
              ;;
            Staging)
              export ENV_ALIAS=staging
              ;;
            Production)
              export ENV_ALIAS=prod
              ;;
          esac

          echo "guapa"
